# -*- coding: utf-8 -*-
"""python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-VEgyExKIggC16eBi0xeFlkF1ntn6mKd
"""

x = 10

x

mysub = "python"

_mycity = "solan"

_mycity

import keyword
print(keyword.kwlist)

import keyword
print(keyword.kwlist)

x = 1
type(x)

y = 0.0
type(y)

z = 3+4j
type(z)

x = "solan"
type(x)

a = True
type(a)

e = None
type(e)

ls

#single quotes
my_sub = 'Generative AI'
type(my_sub)

#double quotes
my_cl = "shoolini University"
type(my_cl)

#triple quotes
my_sen = '''this is used for sentences with multiple lines, this ia also called string'''
type(my_sen)

my_sub = 'Machine learning'
len(my_sub)

my_sub = 'Machine learning'
my_sub[0]

my_sub = 'Machine learning'
my_sub[5]

my_sub = 'machine learning'
my_sub[0:7]

my_sub[0:10]

my_sub = 'Machine learning'
my_sub[-1::-1]

my_sub = 'PYTHON'
my_sub.lower()

#upper() -- this method convert string into uppercase
my_string = 'machine learning'
my_string.upper()

#count() -- this method count the number of character
my_string.count('a')

my_string.count(' ')

mylist = [78, 89, 'apple', 3.14]
type(mylist)

fruitlist = ['apple', 'banana', 'mango']
type(fruitlist)

mylist = [78, 89, 'apple', 3.14]
len(mylist)

print(mylist)

listy = [78, 89, 23, 75, 22]
listy.sort()
print(listy)

listy[0]

my_list = [78, 89, 23, 24, 56, 78]
print(my_list[0:4:1])
print(my_list[0:4])

print(my_list[0:])

my_list[::-1]

list1 = [7, 8, 5, 4, 2]
min(list1)

max(list1)

sum(list1)

sorted(list1)

my_list = [89, 90, 56, 49, 69]
sorted(my_list, reverse = True)

list1 = [89, 76, 56]
list1.append(45)
print(list1)

list1 = [75, 34, 28]
list2 = [56, 74, 74]
list1.extend(list2)
list1

my_list =[65, 46, 46, 45]
my_list.sort()
my_list

my_list.sort(reverse = True)

list1 = [90, 78, 25, 23, 96]
list1.pop(1)

my_list = [87,39,56,52]
my_list.reverse()
my_list

my_dict = {"hp" : "shm", "up" : "luck"}
my_dict["hp"]

my_dict["up"]

list(my_dict.keys())

list(my_dict.values())

list(my_dict.items())

list(my_dict.get("up"))

my_dict = {"hp" : "shm", "up" : "luck"}
print(my_dict.get("mp"))

print(my_dict.get("mp", "Not found"))

my_dict.update({"mp" : "bhopal"})
print(my_dict)

my_dict.update({"hp" : "solan"})
print(my_dict)

age = int(input("enter your age:"))
if age>60:
  print("Too old to marry unless you are billionare")
elif age<18:
  print("Too young to marrage unless you are rajasthani or your name is aryan")
else:
  print("you can marry if you have 100k$ job")

my_sub = 'python'
print(my_sub[0])

for i in my_sub:
 print(i)

my_list = [78, 89, 23, 24, 56, 78]
for i in my_list:
   print(i)

for i in range(0, 6, 1):
   print(i)

for i in range(0,6):
 print(i)

for i in range(6):
  print(i)

i = 0
while i<5:
 print(i)
 i+=1

i = 0
while i<5:
   i+=1
   if i == 3:
    break
   else:
    print(i)

i = 0
while i<5:
   i+=1
   if i == 3:
    continue
    print(i)
   else:
    print(i)

i = 0
while i<5:
  i+=1
  if i == 3:
    pass
    print(i)
  else:
    print(i)

def add():
  a = int(input('enter first no: '))
  b = int(input('enter second no: '))
  return a+b

print(add())

def calculation(a, b):
  print("substraction", a-b)
  print("addition", a+b)
  print("multiplication", a*b)
  print("division", a/b)

calculation(10, 6)

def area_perimeter(width = 4, height = 8):
  area = width*height
  perimeter = 2*(width*height)
  return 'area is', area, 'and perimeter is', perimeter

area_perimeter()

area_perimeter(10,20)

def interest(p, r, t):
  i = (p*r*t)/100
  return i

interest(r = 10, t = 2, p = 20000)

interest(1000, t = 2, r = 10)

import matplotlib.pyplot as plt
import numpy as np
xpoint = np.array([1,3])
ypoint = np.array([2,4])
plt.plot(xpoint, ypoint)
plt.show()

cgpa = np.array([6,7,8,9,10])
package = np.array([5, 6, 5, 8, 9])
plt.plot(cgpa, package, "h:r", ms= 15, mec = "orange", linewidth = 5)
plt.xlabel("cgpa")
plt.ylabel("package(lpa)")
plt.title("Shoolini's student data")
plt.show()

import matplotlib.pyplot as plt
import numpy as np
fruit = np.array(['apple', 'banana','orange','watermelon'])
quantity = np.array([100, 120, 90, 80])
color = np.array(['red','yellow','orange', 'green'])
plt.bar(fruit, quantity, color = color)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
fruit = np.array(['apple', 'banana','orange','watermelon'])
quantity = np.array([100, 120, 90, 80])
color = np.array(['red','yellow','orange', 'green'])
plt.barh(fruit, quantity, color = color)
plt.show()

from re import M
#pie plot
fruit_percentage = np.array([10, 20, 30, 40])
fruit = np.array(['apple', 'banana','orange','watermelon'])
color = np.array(['red','yellow','orange', 'green'])
myexplode = np.array([0, 0, 0, 0.3])
plt.pie(fruit_percentage, labels = fruit, autopct="%1.1f%%", colors=color, explode= myexplode)
plt.legend( title = "Fruit", loc = "best")
plt.show()

age_of_car = np.array([1,2,3,4,5,6,7,8,9,10])
speed_of_car = np.array([190, 180, 160, 140, 130, 120, 110, 100, 90, 80])
plt.scatter(age_of_car, speed_of_car, color = "red")
plt.xlabel("age of car")
plt.ylabel("speed of car")
plt.title("age vs speed")
plt.show()

import numpy as np
x = np.random.randint(40, 100,(1, 200))
x = x.flatten()
print(x)

plt.hist(x, bins = 20, color = "red")
plt.xlabel("marks")
plt.ylabel("frequency")
plt.title("marks distribution")
plt.show()

# pandas it is a python libraray- it is used for data manipulition
import pandas as pd

fruit_list = ["apple", "banana","grapes","mango"]
my_series = pd.Series(fruit_list)
print(my_series)

list_of_list = [["apple", 100],["mango", 120],["orange",150]]
df = pd.DataFrame(list_of_list, columns= ["fruit", "price"])
df

import pandas as pd
df = pd.read_csv("/content/drive/MyDrive/data/imdb_data.csv")
df

df.shape

df.head(300)

df.tail(100)

df.sample()

df.sample(10)

df.info()

#how does the data look like mathematicly
df.describe()

import numpy as np
from numpy.linalg import norm

a = np.array([2,1,2,3,2,9])
b = np.array([3,4,2,4,5,5])

cosine = np.dot(a,b)/(norm(a)*norm(b))
print(cosine)

g